name: Build CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions/setup-rust@v2
        with:
          rust-version: 'stable'

      - name: Build project
        run: cargo build --verbose
